services:
  db:
    image: postgres:17
    container_name: ratemypet-db
    environment:
      POSTGRES_USER: ratemypet
      POSTGRES_PASSWORD: ratemypet
      POSTGRES_DB: ratemypet_dev
    ports:
      - 5432:5432
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ratemypet -d ratemypet_dev"]
      interval: 2s
      timeout: 3s
      retries: 20

  api:
    build:
      context: .
      dockerfile: dockerfile.dev
    container_name: ratemypet-api
    command: sh -c "npm ci && npm run dev:docker"
    environment:
      NODE_ENV: development
      DATABASE_URL: postgres://ratemypet:ratemypet@db:5432/ratemypet_dev?sslmode=disable
    volumes:
      - ./backend/src:/usr/ratemypet/backend/src
      - ./backend/src/main/layers/infra/db/migrations:/usr/ratemypet/backend/src/main/layers/infra/db/migrations
      - node_modules:/usr/ratemypet/node_modules
    ports:
      - "8080:8000"
    depends_on:
      db:
        condition: service_healthy

volumes:
  pgdata:
  node_modules: