services:
  db:
    image: postgres:17
    container_name: ratemypet-db
    environment:
      POSTGRES_USER: ratemypet
      POSTGRES_PASSWORD: ratemypet
      POSTGRES_DB: ratemypet_dev
    ports:
      - 5432:5432
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ratemypet -d ratemypet_dev"]
      interval: 2s
      timeout: 3s
      retries: 20

volumes:
  pgdata: